"""initial schema

Revision ID: d47df36f7f43
Revises: 
Create Date: 2026-08-11 20:51:48.242991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd47df36f7f43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('futures_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('underlying', sa.String(length=64), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ltp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('oi', sa.BigInteger(), nullable=False),
    sa.Column('oi_change', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying', 'expiry', 'datetime', name='uq_futures_identity')
    )
    op.create_index(op.f('ix_futures_data_datetime'), 'futures_data', ['datetime'], unique=False)
    op.create_index(op.f('ix_futures_data_expiry'), 'futures_data', ['expiry'], unique=False)
    op.create_index(op.f('ix_futures_data_underlying'), 'futures_data', ['underlying'], unique=False)
    op.create_index('ix_futures_lookup', 'futures_data', ['underlying', 'expiry', 'datetime'], unique=False)
    op.create_table('india_vix',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interval', 'datetime', name='uq_india_vix_interval_dt')
    )
    op.create_index(op.f('ix_india_vix_datetime'), 'india_vix', ['datetime'], unique=False)
    op.create_index(op.f('ix_india_vix_interval'), 'india_vix', ['interval'], unique=False)
    op.create_table('market_ticks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ask', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('oi', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_ticks_symbol'), 'market_ticks', ['symbol'], unique=False)
    op.create_index('ix_market_ticks_symbol_timestamp', 'market_ticks', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_ticks_timestamp'), 'market_ticks', ['timestamp'], unique=False)
    op.create_table('option_chain',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('underlying', sa.String(length=64), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('ltp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('oi', sa.BigInteger(), nullable=False),
    sa.Column('oi_change', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('iv', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ask', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying', 'expiry', 'datetime', 'strike', 'option_type', name='uq_option_chain_snapshot_identity')
    )
    op.create_index(op.f('ix_option_chain_datetime'), 'option_chain', ['datetime'], unique=False)
    op.create_index(op.f('ix_option_chain_expiry'), 'option_chain', ['expiry'], unique=False)
    op.create_index('ix_option_chain_lookup', 'option_chain', ['underlying', 'expiry', 'datetime', 'strike'], unique=False)
    op.create_index(op.f('ix_option_chain_option_type'), 'option_chain', ['option_type'], unique=False)
    op.create_index(op.f('ix_option_chain_strike'), 'option_chain', ['strike'], unique=False)
    op.create_index(op.f('ix_option_chain_underlying'), 'option_chain', ['underlying'], unique=False)
    op.create_table('option_ohlc',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('underlying', sa.String(length=64), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('oi', sa.BigInteger(), nullable=False),
    sa.Column('oi_change', sa.BigInteger(), nullable=False),
    sa.Column('iv', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying', 'strike', 'expiry', 'option_type', 'interval', 'datetime', name='uq_option_ohlc_identity')
    )
    op.create_index(op.f('ix_option_ohlc_datetime'), 'option_ohlc', ['datetime'], unique=False)
    op.create_index(op.f('ix_option_ohlc_expiry'), 'option_ohlc', ['expiry'], unique=False)
    op.create_index(op.f('ix_option_ohlc_interval'), 'option_ohlc', ['interval'], unique=False)
    op.create_index('ix_option_ohlc_lookup', 'option_ohlc', ['underlying', 'expiry', 'strike', 'option_type', 'datetime'], unique=False)
    op.create_index(op.f('ix_option_ohlc_option_type'), 'option_ohlc', ['option_type'], unique=False)
    op.create_index(op.f('ix_option_ohlc_strike'), 'option_ohlc', ['strike'], unique=False)
    op.create_index(op.f('ix_option_ohlc_underlying'), 'option_ohlc', ['underlying'], unique=False)
    op.create_table('spot_ohlc',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'datetime', name='uq_spot_ohlc_symbol_interval_dt')
    )
    op.create_index(op.f('ix_spot_ohlc_datetime'), 'spot_ohlc', ['datetime'], unique=False)
    op.create_index(op.f('ix_spot_ohlc_interval'), 'spot_ohlc', ['interval'], unique=False)
    op.create_index(op.f('ix_spot_ohlc_symbol'), 'spot_ohlc', ['symbol'], unique=False)
    op.create_index('ix_spot_ohlc_symbol_interval_dt', 'spot_ohlc', ['symbol', 'interval', 'datetime'], unique=False)
    op.create_table('trade_signals',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying', sa.String(length=64), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('signal_type', sa.Enum('CE_ENTRY', 'PE_ENTRY', 'EXIT', 'PARTIAL_EXIT', 'SL_UPDATE', name='signal_type'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_trade_signals_entry_time'), 'trade_signals', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trade_signals_signal_type'), 'trade_signals', ['signal_type'], unique=False)
    op.create_table('trade_execution',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('BACKTEST', 'PAPER', 'LIVE', name='trade_mode'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='trade_status'), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('charges', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['trade_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_trade_execution_mode'), 'trade_execution', ['mode'], unique=False)
    op.create_index(op.f('ix_trade_execution_status'), 'trade_execution', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_execution_status'), table_name='trade_execution')
    op.drop_index(op.f('ix_trade_execution_mode'), table_name='trade_execution')
    op.drop_table('trade_execution')
    op.drop_index(op.f('ix_trade_signals_signal_type'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_entry_time'), table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_index('ix_spot_ohlc_symbol_interval_dt', table_name='spot_ohlc')
    op.drop_index(op.f('ix_spot_ohlc_symbol'), table_name='spot_ohlc')
    op.drop_index(op.f('ix_spot_ohlc_interval'), table_name='spot_ohlc')
    op.drop_index(op.f('ix_spot_ohlc_datetime'), table_name='spot_ohlc')
    op.drop_table('spot_ohlc')
    op.drop_index(op.f('ix_option_ohlc_underlying'), table_name='option_ohlc')
    op.drop_index(op.f('ix_option_ohlc_strike'), table_name='option_ohlc')
    op.drop_index(op.f('ix_option_ohlc_option_type'), table_name='option_ohlc')
    op.drop_index('ix_option_ohlc_lookup', table_name='option_ohlc')
    op.drop_index(op.f('ix_option_ohlc_interval'), table_name='option_ohlc')
    op.drop_index(op.f('ix_option_ohlc_expiry'), table_name='option_ohlc')
    op.drop_index(op.f('ix_option_ohlc_datetime'), table_name='option_ohlc')
    op.drop_table('option_ohlc')
    op.drop_index(op.f('ix_option_chain_underlying'), table_name='option_chain')
    op.drop_index(op.f('ix_option_chain_strike'), table_name='option_chain')
    op.drop_index(op.f('ix_option_chain_option_type'), table_name='option_chain')
    op.drop_index('ix_option_chain_lookup', table_name='option_chain')
    op.drop_index(op.f('ix_option_chain_expiry'), table_name='option_chain')
    op.drop_index(op.f('ix_option_chain_datetime'), table_name='option_chain')
    op.drop_table('option_chain')
    op.drop_index(op.f('ix_market_ticks_timestamp'), table_name='market_ticks')
    op.drop_index('ix_market_ticks_symbol_timestamp', table_name='market_ticks')
    op.drop_index(op.f('ix_market_ticks_symbol'), table_name='market_ticks')
    op.drop_table('market_ticks')
    op.drop_index(op.f('ix_india_vix_interval'), table_name='india_vix')
    op.drop_index(op.f('ix_india_vix_datetime'), table_name='india_vix')
    op.drop_table('india_vix')
    op.drop_index('ix_futures_lookup', table_name='futures_data')
    op.drop_index(op.f('ix_futures_data_underlying'), table_name='futures_data')
    op.drop_index(op.f('ix_futures_data_expiry'), table_name='futures_data')
    op.drop_index(op.f('ix_futures_data_datetime'), table_name='futures_data')
    op.drop_table('futures_data')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
